configure add checks for cairo-egl libraries

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -625,6 +625,7 @@ BACKEND_NAME
 WARN_FLAGS
 BUILD_SERVER
 BUILD_GRAPHICS
+WITH_CAIRO_EGL
 WITH_WRASTER
 WITH_GLITZ
 GLITZ_WGL_LIBS
@@ -635,6 +636,8 @@ GLITZ_LIBS
 GLITZ_CFLAGS
 FONTCONFIG_LIBS
 FONTCONFIG_CFLAGS
+CAIRO_EGL_LIBS
+CAIRO_EGL_CFLAGS
 CAIRO_GLITZ_LIBS
 CAIRO_GLITZ_CFLAGS
 CAIRO_WIN32_LIBS
@@ -774,6 +777,8 @@ CAIRO_WIN32_CFLAGS
 CAIRO_WIN32_LIBS
 CAIRO_GLITZ_CFLAGS
 CAIRO_GLITZ_LIBS
+CAIRO_EGL_CFLAGS
+CAIRO_EGL_LIBS
 FONTCONFIG_CFLAGS
 FONTCONFIG_LIBS
 GLITZ_CFLAGS
@@ -1470,6 +1475,10 @@ Some influential environment variables:
               C compiler flags for CAIRO_GLITZ, overriding pkg-config
   CAIRO_GLITZ_LIBS
               linker flags for CAIRO_GLITZ, overriding pkg-config
+  CAIRO_EGL_CFLAGS
+              C compiler flags for CAIRO_EGL, overriding pkg-config
+  CAIRO_EGL_LIBS
+              linker flags for CAIRO_EGL, overriding pkg-config
   FONTCONFIG_CFLAGS
               C compiler flags for FONTCONFIG, overriding pkg-config
   FONTCONFIG_LIBS
@@ -6536,6 +6545,77 @@ $as_echo "yes" >&6; }
 fi
 
 pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for cairo-egl" >&5
+$as_echo_n "checking for cairo-egl... " >&6; }
+
+if test -n "$CAIRO_EGL_CFLAGS"; then
+    pkg_cv_CAIRO_EGL_CFLAGS="$CAIRO_EGL_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"cairo-egl\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "cairo-egl") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_CAIRO_EGL_CFLAGS=`$PKG_CONFIG --cflags "cairo-egl" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$CAIRO_EGL_LIBS"; then
+    pkg_cv_CAIRO_EGL_LIBS="$CAIRO_EGL_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"cairo-egl\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "cairo-egl") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_CAIRO_EGL_LIBS=`$PKG_CONFIG --libs "cairo-egl" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        CAIRO_EGL_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "cairo-egl" 2>&1`
+        else
+	        CAIRO_EGL_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "cairo-egl" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$CAIRO_EGL_PKG_ERRORS" >&5
+
+	have_cairo_egl=no
+elif test $pkg_failed = untried; then
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	have_cairo_egl=no
+else
+	CAIRO_EGL_CFLAGS=$pkg_cv_CAIRO_EGL_CFLAGS
+	CAIRO_EGL_LIBS=$pkg_cv_CAIRO_EGL_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+	have_cairo_egl=yes
+fi
+
+pkg_failed=no
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for fontconfig" >&5
 $as_echo_n "checking for fontconfig... " >&6; }
 
@@ -6605,7 +6685,7 @@ else
 $as_echo "yes" >&6; }
 	have_fontconfig=yes
 fi
-
+WITH_CAIRO_EGL=no
 if test "$have_cairo" = no; then
   { $as_echo "$as_me:${as_lineno-$LINENO}: checking for cairo_create in -lcairo" >&5
 $as_echo_n "checking for cairo_create in -lcairo... " >&6; }
@@ -6777,6 +6857,50 @@ if test "x$ac_cv_lib_cairo_cairo_win32_surface_create" = xyes; then :
 fi
 
 fi
+
+if test "$have_cairo_egl" = no; then
+  { $as_echo "$as_me:${as_lineno-$LINENO}: checking for cairo_egl_surface_create in -lcairo" >&5
+$as_echo_n "checking for cairo_egl_surface_create in -lcairo... " >&6; }
+if ${ac_cv_lib_cairo_cairo_egl_surface_create+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcairo  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char cairo_egl_surface_create ();
+int
+main ()
+{
+return cairo_egl_surface_create ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  ac_cv_lib_cairo_cairo_egl_surface_create=yes
+else
+  ac_cv_lib_cairo_cairo_egl_surface_create=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_cairo_cairo_egl_surface_create" >&5
+$as_echo "$ac_cv_lib_cairo_cairo_egl_surface_create" >&6; }
+if test "x$ac_cv_lib_cairo_cairo_egl_surface_create" = xyes; then :
+  have_cairo_egl=yes
+fi
+
+fi
+
 
 #--------------------------------------------------------------------
 # XRender support
@@ -7205,7 +7329,6 @@ $as_echo_n "checking Cairo backend... " >&6; }
       CAIRO_LIBS="$CAIRO_LIBS $FONTCONFIG_LIBS"
       CAIRO_CFLAGS="$CAIRO_CFLAGS $FONTCONFIG_CFLAGS"
     fi
-
     if test "$have_xrender" = yes; then
       if test $BUILD_SERVER = x11 -a "x$have_cairo_xlib" = "xyes"; then
 
@@ -7213,6 +7336,16 @@ $as_echo "#define XRENDER 1" >>confdefs.h
 
         CAIRO_LIBS="$CAIRO_LIBS -lXrender"
       fi
+    fi
+    if test $BUILD_SERVER = wayland -a "x$have_cairo_egl" = "xyes"; then
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: Enabling Cairo egl support" >&5
+$as_echo "$as_me: Enabling Cairo egl support" >&6;}
+
+$as_echo "#define HAVE_CAIRO_EGL 1" >>confdefs.h
+
+        CAIRO_LIBS="$CAIRO_LIBS -lEGL -lwayland-egl"
+        WITH_CAIRO_EGL=yes
+
     fi
     if test "x$WITH_GLITZ" = "xyes" -a "x$have_cairo_glitz" = "xyes"; then
       if test $BUILD_SERVER = win32 -a "x$have_cairo_win32" = "xyes"; then
